name: Deploy FastAPI Backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend

      # Build & deploy Docker image to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud auth activate-service-account --key-file=$GCP_SA_KEY
          gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/fastapi-backend ./backend
          gcloud run deploy fastapi-backend --image gcr.io/$GCP_PROJECT_ID/fastapi-backend:latest --region us-central1 --platform managed --allow-unauthenticated
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
