name: Deploy FastAPI Backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: Backend

      # Authenticate with GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Build & Push Docker image
      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/artistsphere-cdab2/my-backend:latest ./Backend
      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: my-backend
          image: gcr.io/artistsphere-cdab2/my-backend:latest
          region: us-central1
