name: Deploy FastAPI Backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install -r requirements.txt
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service: fastapi-backend
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-backend:latest
          region: us-central1
          credentials: ${{ secrets.GCP_SA_KEY }}
