name: Deploy FastAPI Backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Authenticate with GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: artistsphere-cdab2
          export_default_credentials: true

      # Build & Push Docker image
      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/artistsphere-cdab2/my-backend:latest .

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: my_backend
          image: gcr.io/artistsphere-cdab2/my-backend:latest
          region: us-central1
