name: Deploy React App

on:
  push:
    branches: [ main ]  # triggers on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # GitHub server OS

    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the React app
      - name: Build React app
        run: npm run build

      # 5. Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}   # 🔥 Add this
          channelId: live
