name: Deploy React App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      # Build React app
      - name: Build React app
        run: npm run build
        working-directory: ./frontend

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
<<<<<<< HEAD
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}   # 🔥 Add this
=======
          entryPoint: ./frontend        # <- points to folder with firebase.json
>>>>>>> c982d38fbde78e5e640439bf65840f20fc4f969a
          channelId: live
          projectId: <YOUR_FIREBASE_PROJECT_ID>
